"""Parse a walkforward JSON, emit a markdown health report, and gate via exit code.

Run after `python -m trading_bot.multi_strategy_backtest --walkforward ...`
finishes. Reads the most recent JSON in ``backtest_results/`` (or a path
passed as ``--input``), checks the synthetic ``_portfolio`` strategy's
profit-factor CI lower bound, and writes a markdown report. Exits with
code 1 (alert) when the lower bound falls below ``--min-pf-lower``
(default 1.0); otherwise exits 0 (healthy).

Used by ``.github/workflows/weekly-walkforward.yml``. Open a draft PR
with the report on alert; otherwise the report is uploaded as an
artifact only.
"""

from __future__ import annotations

import argparse
import glob
import json
import sys
from dataclasses import dataclass
from pathlib import Path

PORTFOLIO_KEY: str = "_portfolio"


@dataclass(frozen=True)
class StrategyHealth:
    sid: str
    trades: int
    win_rate: float | None
    profit_factor: float | None
    pf_lower: float | None
    pf_upper: float | None
    return_pct: float | None
    sharpe: float | None


def load_latest_json(input_arg: str | None) -> Path:
    if input_arg:
        return Path(input_arg)
    candidates = sorted(glob.glob("backtest_results/walkforward_*.json"))
    if not candidates:
        raise SystemExit("No walkforward_*.json found in backtest_results/")
    return Path(candidates[-1])


def extract(payload: dict) -> list[StrategyHealth]:
    aggregate: dict = payload.get("aggregate", {})
    bootstrap: dict = payload.get("bootstrap", {})
    out: list[StrategyHealth] = []
    for sid, agg in aggregate.items():
        ci = bootstrap.get(sid, {}).get("profit_factor")
        out.append(
            StrategyHealth(
                sid=sid,
                trades=int(agg.get("trades", 0)),
                win_rate=_as_float(agg.get("win_rate")),
                profit_factor=_as_float(agg.get("profit_factor")),
                pf_lower=_as_float(ci.get("lower")) if ci else None,
                pf_upper=_as_float(ci.get("upper")) if ci else None,
                return_pct=_as_float(agg.get("return_pct")),
                sharpe=_as_float(agg.get("sharpe_approx")),
            )
        )
    return out


def render_markdown(
    payload: dict,
    health: list[StrategyHealth],
    min_pf_lower: float,
    portfolio_alert: bool,
) -> str:
    cfg = payload.get("config", {})
    lines: list[str] = [
        f"# Weekly walkforward — {payload.get('from_date')} → {payload.get('to_date')}",
        "",
        f"- Window: {cfg.get('window_days')}d  •  Step: {cfg.get('step_days')}d",
        f"- Bootstrap samples: {cfg.get('bootstrap_samples')}  "
        f"•  CI: {int(float(cfg.get('bootstrap_ci', 0.95)) * 100)}%",
        f"- Min portfolio PF lower-bound for healthy: {min_pf_lower:.2f}",
        "",
    ]
    if portfolio_alert:
        lines += [
            "## ⚠️  Portfolio CI degraded",
            "",
            "Portfolio PF CI lower bound has fallen below the threshold. "
            "Investigate per-sleeve breakdown below; consider reviewing the "
            "[Return improvement TODOs](../../trading_bot/docs).",
            "",
        ]
    else:
        lines += ["## ✅  Portfolio CI healthy", ""]

    lines += [
        "| Strategy | Trades | WR | PF | PF CI 95% | Return | Sharpe |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for h in sorted(health, key=lambda x: (x.sid != PORTFOLIO_KEY, x.sid)):
        ci_str = (
            f"[{h.pf_lower:.3f}, {h.pf_upper:.3f}]"
            if h.pf_lower is not None and h.pf_upper is not None
            else "—"
        )
        lines.append(
            "| `{sid}` | {trades} | {wr} | {pf} | {ci} | {ret} | {sh} |".format(
                sid=h.sid,
                trades=h.trades,
                wr=_fmt_pct(h.win_rate),
                pf=_fmt(h.profit_factor),
                ci=ci_str,
                ret=_fmt_pct(h.return_pct),
                sh=_fmt(h.sharpe),
            )
        )

    lines += ["", "<sub>Generated by `scripts/walkforward_health_check.py`.</sub>"]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input", default=None, help="Path to walkforward JSON (default: latest)"
    )
    parser.add_argument(
        "--out", default="walkforward_health.md", help="Markdown report path"
    )
    parser.add_argument(
        "--min-pf-lower",
        type=float,
        default=1.0,
        help="Alert when _portfolio PF CI lower bound < this value",
    )
    args = parser.parse_args()

    json_path = load_latest_json(args.input)
    with open(json_path) as f:
        payload = json.load(f)

    health = extract(payload)
    portfolio = next((h for h in health if h.sid == PORTFOLIO_KEY), None)
    portfolio_alert: bool = (
        portfolio is None
        or portfolio.pf_lower is None
        or portfolio.pf_lower < args.min_pf_lower
    )

    md = render_markdown(payload, health, args.min_pf_lower, portfolio_alert)
    Path(args.out).write_text(md)

    print(f"Wrote {args.out} — portfolio_alert={portfolio_alert}")
    if portfolio:
        print(
            f"_portfolio: PF={portfolio.profit_factor} "
            f"CI=[{portfolio.pf_lower}, {portfolio.pf_upper}] "
            f"trades={portfolio.trades}"
        )
    else:
        print("No _portfolio key in walkforward output.")

    return 1 if portfolio_alert else 0


def _as_float(v: object) -> float | None:
    if v is None:
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _fmt(v: float | None) -> str:
    return f"{v:.3f}" if v is not None else "—"


def _fmt_pct(v: float | None) -> str:
    return f"{v * 100:.1f}%" if v is not None else "—"


if __name__ == "__main__":
    sys.exit(main())
